CREATE EXTENSION IF NOT EXISTS vector;

SELECT c.full_name,
         COUNT(t.transaction_id) AS tx_count,
         SUM(t.amount)           AS total_volume
  FROM customers c
  JOIN accounts a ON a.customer_id = c.customer_id
  JOIN transactions t ON t.account_id = a.account_id
  GROUP BY c.customer_id, c.full_name
  ORDER BY total_volume DESC
  LIMIT 5;

SELECT 
    cmetadata->>'name' AS schema_name, 
    cmetadata->>'type' AS doc_type, 
    SUBSTRING(document, 1, 60) || '...' AS preview_text 
FROM langchain_pg_embedding;

SELECT DISTINCT account_type FROM accounts;


-- Generated by Gemini
WITH customer_wealth AS (
    -- Calculate total balance and check if they have an active checking account
    SELECT 
        c.customer_id,
        c.full_name,
        SUM(a.balance) AS total_balance,
        BOOL_OR(a.account_type = 'checking' AND a.status = 'active') AS qualifies
    FROM customers c
    JOIN accounts a ON c.customer_id = a.customer_id
    GROUP BY c.customer_id, c.full_name
),
transaction_metrics AS (
    -- Calculate largest recent debit and total lifetime transfers
    SELECT 
        a.customer_id,
        MAX(CASE WHEN t.transaction_type = 'debit' AND t.transaction_date >= NOW() - INTERVAL '30 days' THEN t.amount ELSE 0 END) AS max_recent_debit,
        COUNT(CASE WHEN t.transaction_type = 'transfer' THEN 1 END) AS total_transfers
    FROM accounts a
    JOIN transactions t ON a.account_id = t.account_id
    GROUP BY a.customer_id
)
SELECT 
    cw.full_name,
    cw.total_balance,
    COALESCE(tm.max_recent_debit, 0.00) AS max_debit_last_30_days,
    COALESCE(tm.total_transfers, 0) AS total_lifetime_transfers
FROM customer_wealth cw
LEFT JOIN transaction_metrics tm ON cw.customer_id = tm.customer_id
WHERE cw.qualifies = TRUE
ORDER BY cw.total_balance DESC
LIMIT 5;


-- Genearted by RAG
SELECT                                                                                                                     │
   c.full_name,                                                                                                             │
   wealth.total_balance,                                                                                                    │
   COALESCE(tx.max_debit_30d, 0) AS largest_debit_30d,                                                                      │
   COALESCE(tx.transfer_count, 0) AS total_transfers                                                                        │
 FROM customers c                                                                                                           │
 JOIN (                                                                                                                     │
SELECT                                                                                                                   │
     a.customer_id,                                                                                                         │
     SUM(a.balance) AS total_balance                                                                                        │
   FROM accounts a                                                                                                          │
   GROUP BY a.customer_id                                                                                                   │
 ) wealth ON c.customer_id = wealth.customer_id                                                                             │
 LEFT JOIN (                                                                                                                │
SELECT                                                                                                                   │
     a.customer_id,                                                                                                         │
     MAX(CASE WHEN t.transaction_type = 'debit' AND t.transaction_date >= CURRENT_DATE - INTERVAL '30 days' THEN t.amount   │
 ELSE 0 END) AS max_debit_30d,                                                                                              │
     COUNT(CASE WHEN t.transaction_type = 'transfer' THEN 1 END) AS transfer_count                                          │
   FROM accounts a                                                                                                          │
   JOIN transactions t ON a.account_id = t.account_id                                                                       │
   GROUP BY a.customer_id                                                                                                   │
 ) tx ON c.customer_id = tx.customer_id                                                                                     │
 WHERE EXISTS (                                                                                                             │
SELECT 1                                                                                                                 │
   FROM accounts a2                                                                                                         │
   WHERE a2.customer_id = c.customer_id                                                                                     │
     AND a2.account_type = 'checking'                                                                                       │
     AND a2.status = 'active'                                                                                               │
 )                                                                                                                          │
 ORDER BY wealth.total_balance DESC                                                                                         │
 LIMIT 5;

